// <auto-generated />
using BlazorShop.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorShop.API.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorShop.API.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CarrinhoItems");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fa-mobile-alt",
                            Nome = "Celulares"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fa-laptop",
                            Nome = "Computadores"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fa-headphones-alt",
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fa-gamepad",
                            Nome = "Videogames"
                        });
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Celular Samsung Galaxy S20",
                            ImagemUrl = "https://i.zst.com.br/thumbs/12/13/3e/-733839784.jpg",
                            Nome = "Samsung Galaxy S20",
                            Preco = 599.99m,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Celular Iphone 15",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/486277/iphone-15-apple-128gb-preto-tela-de-6-1-camera-dupla-de-48mp-ios-mtp03be-a_1695657254_original.jpg",
                            Nome = "Iphone 15",
                            Preco = 1199.99m,
                            Quantidade = 110
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descricao = "Celular Xiaomi Redmi Note 10",
                            ImagemUrl = "https://oneclick.com.py/upload/produtos/be88c00976d071c8406046514fdb4412.jpg",
                            Nome = "Xiaomi Redmi Note 10",
                            Preco = 359.85m,
                            Quantidade = 120
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Descricao = "Computador Gamer Fácil Intel Core I5 3a Geração, 8GB, GTX 1650 4GB, SSD 120GB, Fonte 500w",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/sync_mirakl/169050/Computador-Gamer-F-cil-Intel-Core-I5-3a-Gera-o-8GB-GTX-1650-4GB-SSD-120GB-Fonte-500w_1669061915_gg.jpg",
                            Nome = "Computador Gamer Intel Core I5",
                            Preco = 2599.78m,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descricao = "Computador Gamer Fácil Intel Core I7 3a Geração, 8GB, GTX 1650 4GB, SSD 120GB, Fonte 500w",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/sync_mirakl/418694/PC-Gamer-Enifler-Completo-Intel-Core-I7-16GB-GTX-1050TI-4GB-SSD-480GB-Windows-10-Monitor-21-5-Kit-Gamer-Teclado-Mouse-E-Headset-Hayom_1685449128_g.jpg",
                            Nome = "Computador Gamer Intel Core I7",
                            Preco = 3599.36m,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descricao = "A linha de produtos Bright conta com qualidade e design para facilitar seu dia a dia.\r\n\r\nO Hub 4 portas Bright possui tamanho compacto, compatível com USB 2.0 ",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/104620/-mini-hub-usb-bright-4-portas-2-0-preto-59-_1569853689_gg.jpg",
                            Nome = "HUB USB 2.0 Bright, 4 Portas, Preto",
                            Preco = 19.41m,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            Descricao = "O Headset Gamer Redragon Lamia possui um design único, com iluminação RGB Chroma inteligente, que proporciona uma experiência visual incrível.",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/115413/headset-gamer-redragon-lamia-rgb-drivers-40mm-h320rgb-1-_1595016849_gg.jpg",
                            Nome = "Headset Gamer Redragon Lamia, RGB, 7.1, Preto",
                            Preco = 199.53m,
                            Quantidade = 220
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 4,
                            Descricao = "Console Microsoft Xbox Series S, 512GB, Branco. DESEMPENHO DE ÚLTIMA GERAÇÃO NO MENOR XBOX DE TODOS\r\nOS TEMPOS",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/sync_mirakl/200089/Console-Microsoft-Xbox-Series-S-512GB-Branco-RRS-00006_1699618095_gg.jpg",
                            Nome = "Xbox Series S",
                            Preco = 2587.82m,
                            Quantidade = 14
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 4,
                            Descricao = "Console Playstation 5, 825GB, Branco",
                            ImagemUrl = "https://images.kabum.com.br/produtos/fotos/238671/console-sony-playstation-5_1634132554_gg.jpg",
                            Nome = "Playstation 5",
                            Preco = 3440.91m,
                            Quantidade = 206
                        });
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cesar"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Elba"
                        });
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Carrinho", b =>
                {
                    b.HasOne("BlazorShop.API.Entities.Usuario", null)
                        .WithOne("Carrinho")
                        .HasForeignKey("BlazorShop.API.Entities.Carrinho", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorShop.API.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("BlazorShop.API.Entities.Carrinho", "Carrinho")
                        .WithMany("Items")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.API.Entities.Produto", "Produto")
                        .WithMany("Items")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Produto", b =>
                {
                    b.HasOne("BlazorShop.API.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Carrinho", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Produto", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BlazorShop.API.Entities.Usuario", b =>
                {
                    b.Navigation("Carrinho");
                });
#pragma warning restore 612, 618
        }
    }
}
